version: '3'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/opt
    links:
    - mongo
    networks:
    - my-network
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
    - mongo-data:/data/db
    - mongo-configdb:/data/configdb
volumes:
  mongo-data:
  mongo-configdb:

networks:
  my-network:
     name : pymongo-bridge1
     driver: bridge

            
