version: '3'
services:
  web:
    build: .
    image: klogambigai/python-mongo:v1
    ports:
    - "5000:5000"
    volumes:
    - .:/opt
    links:
    - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
    - mongo-data:/data/db
    - mongo-configdb:/data/configdb
volumes:
  mongo-data:
  mongo-configdb:
