version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
     - 27017:27017
  springboot-mongodb:
    image: python-mongodb:v1
    container_name: python-mongodb
    ports:
      - 5000:5000
    links:
      - mymongodb 
