version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
     - 27017:27017
  flask:
    build:
      context: python-mongodb
      dockerfile: Dockerfile
      container_name: flask
      image: flask-python:v1
      restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: flaskuser
      MONGODB_HOSTNAME: mongodb
    ports:
      - 5000:5000
    links:
      - mongodb 
